import { type Metadata } from "next";
import GoogleMaps from "~/clients/components/GoogleMaps";

export const metadata: Metadata = {
  title: "Map",
  description: "Generated by create-t3-app",
};

const MapPage = () => {
  // [TODO] get current latitude and longitude from geolocation
  const address = "601 W Cordova St, Vancouver, BC V6B 1G1";

  return <GoogleMaps address={address} />;
};

export default MapPage;
