import Link from "next/link";
import { type Metadata } from "next";
import Button from "~/clients/components/Button";
import Text from "~/clients/components/Text";

export const metadata: Metadata = {
  title: "Map",
  description: "Generated by create-t3-app",
};

const MapPage = () => {
  return (
    <>
      <Text fz="lg" fw={700} mb={20}>
        Map Page
      </Text>
      <Link href={`/`}>
        <Button buttonType="secondary">Back Home</Button>
      </Link>
    </>
  );
};

export default MapPage;
