import { type Metadata } from "next";
import AuthProvider from "../clients/contexts/AuthProvider";
import TrpcProvider from "~/clients/contexts/TrpcProvider";
import MantineProvider from "~/clients/contexts/MantineProvider";
import Header from "~/clients/components/Header";
import "~/styles/globals.css";
import Footer from "~/clients/components/Footer";

export const metadata: Metadata = {
  title: {
    template: "%s | app name",
    default: "Intro | app name",
  },
  description: "Generated by create-t3-app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <TrpcProvider>
          <AuthProvider>
            <MantineProvider>
              <Header />
              {children}
              <Footer />
            </MantineProvider>
          </AuthProvider>
        </TrpcProvider>
      </body>
    </html>
  );
}

export default RootLayout;
