import { type Metadata } from "next";
import Footer from "~/clients/components/Footer";
import Header from "~/clients/components/Header";
import MainWrapper from "~/clients/components/MainWrapper";
import ColorSchemeProvider from "~/clients/providers/ColorSchemeProvider";
import MantineProvider from "~/clients/providers/MantineProvider";
import TrpcProvider from "~/clients/providers/TrpcClient";
import "~/styles/globals.css";
import AuthProvider from "../clients/providers/AuthProvider";

export const metadata: Metadata = {
  title: {
    template: "%s | app name",
    default: "Intro | app name",
  },
  description: "Generated by create-t3-app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <TrpcProvider>
          <AuthProvider>
            <ColorSchemeProvider>
              <MantineProvider>
                <Header />
                <MainWrapper>{children}</MainWrapper>
                <Footer />
              </MantineProvider>
            </ColorSchemeProvider>
          </AuthProvider>
        </TrpcProvider>
      </body>
    </html>
  );
}

export default RootLayout;
