import Link from "next/link";
import { type Metadata } from "next";
import Button from "~/clients/components/Button";
import Text from "~/clients/components/Text";
import Card from "~/clients/components/FavCards";

export const metadata: Metadata = {
  title: "Map",
  description: "Generated by create-t3-app",
};

const FavPage = () => {
  return (
    <div
      style={{
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "column",
        marginTop: "10%",
      }}
    >
      <Text fz="lg" fw={700} mb={20}>
        Your Favorite Tech Events
      </Text>
      <Card
        title="Coffee.js"
        date="SAT, MAY, 13, 2023, 12:00 PM PDT"
        location="The Golden Horn Turkish Bakery & Cafe"
        description="Join us a regular monthly social for JavaScript enthusiasts. Whether you're a seasoned JavaScript developer or just starting out, Coffee.js is the perfect opportunity to network with like-minded individuals, share your ideas and learn from others."
        imageUrl="https://secure.meetupstatic.com/photos/event/c/7/2/3/clean_511430979.jpeg"
        website="https://www.meetup.com/vancouver-javascript-developers/events/292653989/"
      />
      <Card
        title="test.js"
        date="SAT, MAY, 13, 2023, 12:00 PM PDT"
        location="The Golden Horn Turkish Bakery & Cafe"
        description="Join us a regular monthly social for JavaScript enthusiasts. Whether you're a seasoned JavaScript developer or just starting out, Coffee.js is the perfect opportunity to network with like-minded individuals, share your ideas and learn from others."
        imageUrl="https://secure.meetupstatic.com/photos/event/c/7/2/3/clean_511430979.jpeg"
        website="https://www.meetup.com/vancouver-javascript-developers/events/292653989/"
      />
    </div>
  );
};

export default FavPage;
